# Import Library


In [2]:
import cv2
import numpy as np #202331008_Elma Erista Sinambela

 # Membaca Citra

In [5]:
citra = cv2.imread ('buah.png') #202331008_Elma Erista Sinambela

In [7]:
cv2.imshow("citra asli", citra)
cv2.waitKey(1)
cv2.destroyAllWindows() #202331008_Elma Erista Sinambela

# Dimensi Citra

In [12]:
print(citra.shape)
print(citra.dtype) #202331008_Elma Erista Sinambela

(1200, 1200, 3)
uint8


# Splitting Citra RGB/BGR


In [15]:
b = citra [:,:,0]
g = citra [:,:,1]
r = citra [:,:,2] #202331008_Elma Erista Sinambela

# RGB to Grayscale

In [22]:
panjang = len(citra) #menghitung baris
lebar = len(citra[0]) #menghitung kolom

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] #merah=29,89% ; hijau=58,7% ; biru=11,41%

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey(1)
cv2.destroyAllWindows() #202331008_Elma Erista Sinambela

In [24]:
print(citra) #202331008_Elma Erista Sinambela

[[[107 208 243]
  [ 98 207 249]
  [ 87 204 255]
  ...
  [ 46  58 243]
  [ 32  49 225]
  [ 15  38 205]]

 [[100 212 247]
  [ 93 210 251]
  [ 84 206 254]
  ...
  [ 30  39 237]
  [ 18  32 224]
  [  9  28 214]]

 [[ 88 213 248]
  [ 84 211 250]
  [ 77 207 252]
  ...
  [ 15  22 235]
  [ 10  20 231]
  [ 11  24 232]]

 ...

 [[  4 135 236]
  [  4 136 237]
  [  3 136 237]
  ...
  [  0   0  11]
  [  0   0  11]
  [  0   0  10]]

 [[  6 133 233]
  [  5 135 235]
  [  4 137 236]
  ...
  [  1   1  15]
  [  2   2  15]
  [  2   2  16]]

 [[ 11 134 233]
  [  9 136 235]
  [  5 137 235]
  ...
  [  1   1  16]
  [  4   3  19]
  [  7   6  22]]]


In [26]:
print(citra_gray) #202331008_Elma Erista Sinambela

[[206 207 205 ... 111  99  85]
 [209 208 206 ...  97  87  81]
 [209 208 205 ...  84  81  84]
 ...
 [150 151 151 ...   3   3   2]
 [148 150 151 ...   5   5   6]
 [149 151 151 ...   5   7  10]]


# Grayscale to Binary

In [33]:
panjang = len(citra) #menghitung baris
lebar = len(citra[0]) #menghitung kolom

ambang = 90
citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1 #putih
    else:
        citra_biner[i,j] = 0 #hitam
        

cv2.imshow("citra binary", citra_biner)
cv2.waitKey(1)
cv2.destroyAllWindows() #202331008_Elma Erista Sinambela

In [31]:
print(citra_biner) #202331008_Elma Erista Sinambela

[[1. 1. 1. ... 1. 1. 0.]
 [1. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
